//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CaseAPI.Models.caseproj
{

    public partial class Document : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fUrl;
        public string Url
        {
            get { return fUrl; }
            set { SetPropertyValue<string>(nameof(Url), ref fUrl, value); }
        }
        [Association(@"LicenseReferencesDocument")]
        public XPCollection<License> Licenses { get { return GetCollection<License>(nameof(Licenses)); } }
    }

}
