//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CaseAPI.Models.caseproj
{

    public partial class License : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        Document fDocument;
        [Association(@"LicenseReferencesDocument")]
        public Document Document
        {
            get { return fDocument; }
            set { SetPropertyValue<Document>(nameof(Document), ref fDocument, value); }
        }
    }

}
